---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ros::default]
      - recipe[ros::runit]
    attributes:
      ros:
        #flavor: ros-base
        flavor: desktop-full
